export const food_list = [
  {
    category: "Maggi Items",
    items: [
      { name: "Veg Maggi", price: 30 },
      { name: "Egg Maggi", price: 40 },
      { name: "Chicken Maggi", price: 45 },
      { name: "Corn Maggi", price: 45 },
      { name: "Papper Maggi", price: 45 },
      { name: "Chees Maggi", price: 50 },
    ],
  },
  {
    category: "Sweet Desert",
    items: [
      { name: "Bun Butter Jam", price: 30 },
      { name: "Palkova Bun", price: 25 },
      { name: "Malai Bun", price: 30 },
      { name: "Gulkand Bun", price: 30 },
      { name: "Gulab Jamun Bun", price: 25 },
      { name: "Gulab Jamun", price: 20 },
    ],
  },
  {
    category: "Non Veg Items",
    items: [
      { name: "Bread Omlet", price: 25 },
      { name: "Bread Omlet Chees", price: 30 },
      { name: "Bread Omlet Garlic", price: 40 },
      { name: "Double Egg Bread", price: 40 },
      { name: "Double Egg Chees", price: 45 },
      { name: "Double Egg Mayo", price: 45 },
      { name: "Double Egg Garlic", price: 45 },
      { name: "Double Egg Chees Mayo", price: 50 },
      { name: "Chicken Toast", price: 50 },
      { name: "Chicken Chees Toast", price: 50 },
      { name: "Chicken Mayo Toast", price: 50 },
      { name: "Chicken Garlic Toast", price: 50 },
      { name: "Egg Chicken", price: 50 },
      { name: "Egg Chicken Mayo", price: 60 },
      { name: "Egg Chees Chicken", price: 60 },
      { name: "Double Egg Chicken", price: 60 },
      { name: "Double Egg Chicken Garlic", price: 60 },
      { name: "Double Egg Chicken Mayo", price: 60 },
      { name: "Double Egg Chicken Chees", price: 60 },
      { name: "Ghee Bread Toast", price: 30 },
      { name: "Corn Bread Omlet", price: 30 },
      { name: "Corn Pepper Bread Omlet", price: 30 },
    ],
  },
  {
    category: "Sandwich Items",
    items: [
      { name: "Corn Sandwich", price: 30 },
      { name: "Egg Sandwich", price: 30 },
      { name: "Egg Chees Sandwich", price: 50 },
      { name: "Egg Masala Sandwich", price: 50 },
      { name: "Omplet Masala Sandwich", price: 50 },
      { name: "Double Egg Sandwich", price: 45 },
      { name: "Double Egg Chees Sandwich", price: 55 },
      { name: "Double Egg Masala Sandwich", price: 65 },
      { name: "Double Egg Chees Masala Sandwich", price: 65 },
      { name: "Podi Mass Toast", price: 30 },
      { name: "Podi Mass Mayo Toast", price: 40 },
      { name: "Podi Mass Chees Toast", price: 50 },
      { name: "Boiled Egg Toast", price: 30 },
      { name: "Boiled Egg Mayo Toast", price: 40 },
      { name: "Boiled Egg Chees Toast", price: 50 },
      { name: "Paneer Egg Chees", price: 55 },
      { name: "Corn Egg Chees", price: 70 },
      { name: "Extra Chees", price: 10 },
      { name: "Extra Mayo", price: 10 },
      { name: "Garlic", price: 10 },
      { name: "Khara Sandwich", price: 50 },
    ],
  },
];
